site_name: VADPCM Documentation
site_url: https://depp.github.io/vadpcm/
repo_url: https://github.com/depp/vadpcm/

markdown_extensions:
  - admonition
  - def_list

theme:
  name: material

nav:
  - Introduction: index.md
  - Decode VADPCM: decode.md
  - Encode VADPCM: encode.md
  - VADPCM Codec: codec.md
